traj_chosen_topic: '~traj_chosen'

trajgen:
  trajgen_name: tl

debug:
    ip_topic: 'car_pose'
    flag:
        viz_rollouts: true
        current_path: true
        viz_traj_chosen: true
        viz_cost_fn: true
    viz_rollouts:
        n: 30
        print_stats: true
    traj_chosen_trace:
        rate: 1
